---
title: 'Schedule'
layout: page
---

We have 12 seminar sessions together.

The plan below is provisional. I am happy to adapt the topics, as well as the schedule, to the needs and interests of the students. Likely, we will change some topics and orderings as we go.

| Date             | Topic                                                                                                                |
|--------------------|----------------------------------------------------|
| 22 February 2024 | [Introduction + Where is the digital revolution?](lectures.html#week-1-introduction-where-is-the-digital-revolution) |
| 29 February 2024 | [Text as Data](lectures.html#week-2-text-as-data)                                                                    |
| 07 March 2024    | [Setting up your Development Environment](lectures.html#week-3-setting-up-your-development-environment)              |
| 14 March 2024    | [Introduction to the Command-line](lectures.html#week-4-introduction-to-the-command-line)                            |
| 21 March 2024    | [Basic NLP with Command-line](lectures.html#week-5-basic-nlp-with-command-line) ---\> skip technical preprocessing!  |
| 28 March 2024    | [Learning Regular Expressions](lectures.html#week-6-learning-regular-expressions)                                    |
| 04 April 2024    | *no lecture (Osterpause)*                                                                                            |
| 11 April 2024    | [Working with (your own) Data](lectures.html#week-7-working-with-data) --\> modernize tesseract                      |
| 18 April 2024    | [Ethics and the Evolution of NLP](lectures.html#week-8-ethics-and-the-evolution-of-nlp)                              |
| 25 April 2024    | [Introduction to Python + VS Code](lectures.html#week-9-introduction-to-python)                                      |
| 02 May 2024      | [Data Analysis of Swiss Media](lectures.html#week-10-data-analysis-of-swiss-media)                                   |
| 09 May 2024      | no lecture (Christi Himmelfahrt) [NLP with Python](lectures.html#week-11-nlp-with-python)                            |
| 16 May 2024      | [NLP with Python II + Working Session](lectures.html#week-12-nlp-with-python-ii-working-session)                     |
| 23 May 2024      | [Mini-Project Presentations + Discussion](lectures.html#week-13-mini-project-presentations-discussion)               |
| 30 May 2024      | *no lecture (Fronleichnam)*                                                                                          |